name: Deploy reindexer lambda

on:
  push:
    branches:
      - lambda-production
    paths:
      - "lambda/**"
      - ".github/workflows/deploy-reindexer.yml"

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Lambda dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r lambda/requirements.txt -t lambda/package

      - name: Package Lambda
        run: |
          cp lambda/reindexer.py lambda/package/
          cd lambda/package
          zip -r ../../reindexer.zip .

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: reindexer
          code-artifacts-dir: .
          handler: lambda_function.lambda_handler
          runtime: Python 3.14
          zip-file: reindexer.zip
